server:
  port: 9192


spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/lakeside_hotel_db

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true

  servlet:
    multipart:
    file-size-threshold: 2KB
    max-file-size: 5MB
    max-request-size: 5MB
auth:
  token:
    jwtSecret: 36763979244226452948404D635166546A576D5A7134743777217A25432A462D
    expirationInMils: 3600000


